apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "vreapp.fullname" . }}"
  labels:
    {{- include "vreapp.labels" . | nindent 4 }}

data:
  AUTH0_ID: "{{ .Values.global.keycloak.client_id }}"
  AUTH0_ISSUER: "{{ .Values.global.keycloak.url }}/realms/{{ .Values.global.keycloak.realm }}"
  NEXTAUTH_URL: "https://{{ .Values.global.ingress.host }}:{{ .Values.global.ingress.port }}{{ include "vreapp.basePath" . }}/api/auth"
  NEXTAUTH_URL_INTERNAL: "http://localhost:3000{{ include "vreapp.basePath" . }}/api/auth"
  {{- if .Values.insecureSkipTLSVerification }}
  NODE_TLS_REJECT_UNAUTHORIZED: "0"
  {{- end }}
