apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ include "vreapp.fullname" . }}"
  labels:
    {{- include "vreapp.labels" . | nindent 4 }}

data:
  AUTH0_SECRET: "{{ .Values.global.keycloak.client_secret_key | default "" | b64enc }}"
  SECRET: "{{ .Values.secret_key | default "" | b64enc }}"
