global:
  vreapiEnabled: true
  vreappEnabled: true
  postgresqlEnabled: true

  environment: production

  # base path for each environment (must match VREPaaS/vre-panel/.env.*)
  base_paths:
    test:
      vreapi: "/vre-api-test"
      vreapp: "/vreapp"
    production:
      vreapi: "/vre-api"
      vreapp: "/vreapp"

  # Ingress configuration is shared by vreapi and vreapp.
  # vreapp requires vreapi to be accessible through the same domain
  ingress:
    enabled: true
    className: "nginx"
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    host: "chart-example.local"
    port: ""  # format ":1234"
    tls: []
    #  - secretName: chart-example-tls
    #    host: "chart-example.local"

  postgresql:
    auth:
      username: "vrepaas"
      password: "vrepaas"
      database: "vrepaas"
    service:
      ports:
        postgresql: "5432"

  keycloak:
    url:
    realm: "my-realm"
    client_id: "my-client-id"
    client_secret_key: "my-secret-key"

  argo:
    url:
    namespace: "my-namespace"
    token: "Bearer my-token"

postgresql:
  image:
    tag: "15.3.0"

    initdb:
      scripts:
        create_extension.sh: |
          #!/bin/sh
          export PGPASSWORD=$POSTGRES_POSTGRES_PASSWORD
          psql -U postgres -d $POSTGRES_DATABASE << EOF
            CREATE EXTENSION IF NOT EXISTS postgis;
            SELECT PostGIS_Version();
          EOF

vreapi:
  secret_key:
  auth:
    superuser_email:
    superuser_username:
    superuser_password:

vreapp:
  secret_key:
