global:
  vreapiEnabled: true
  vreappEnabled: true
  postgresqlEnabled: true

  environment: test

  # base path for each environment (must match VREPaaS/vre-panel/.env.*)
  base_paths:
    test:
      vreapi: "/vre-api-test"
      vreapp: "/vreapp"
    production:
      vreapi: "/vre-api"
      vreapp: "/vreapp"

  # Ingress configuration is shared by vreapi and vreapp.
  # vreapp requires vreapi to be accessible through the same domain
  ingress:
    enabled: true
    className: "nginx"
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    host: "chart-example.local"
    tls: []
    #  - secretName: chart-example-tls
    #    host: "chart-example.local"

  postgresql:
    auth:
      username: "vrepaas"
      password: "vrepaas"
      database: "vrepaas"
    service:
      ports:
        postgresql: "5432"

postgresql:
  image:
    tag: "15.3.0"

  primary:
    persistence:
      enabled: false

    initdb:
      scripts:
        create_extension.sh: |
          #!/bin/sh
          export PGPASSWORD=$POSTGRES_POSTGRES_PASSWORD
          psql -U postgres -d $POSTGRES_DATABASE << EOF
            CREATE EXTENSION IF NOT EXISTS postgis;
            SELECT PostGIS_Version();
          EOF
