global:
  vreapiEnabled: true
  vreappEnabled: false
  postgresqlEnabled: true
  nameOverride: ""
  fullnameOverride: ""

  paths:


vreapi:
  ingress:
    enabled: true
    className: "nginx"


vreapp:
  ingress:
    enabled: true
    className: "nginx"