apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ include "vreapi.fullname" . }}"
  labels:
    {{- include "vreapi.labels" . | nindent 4 }}

data:
  K8S_SECRET_CREATOR_TOKEN: "{{ .Values.global.k8s_secret_creator.token | default "" | b64enc }}"
  DJANGO_SUPERUSER_PASSWORD: "{{ .Values.auth.superuser_password | default "" | b64enc }}"
  DJANGO_PASSWORD: "{{ .Values.auth.password | default "" | b64enc }}"
  DJANGO_TOKEN: "{{ .Values.auth.token | default "" | b64enc }}"
  KEYCLOAK_CLIENT_SECRET_KEY: "{{ .Values.global.keycloak.client_secret_key | default "" | b64enc }}"
  SECRET_KEY: "{{ .Values.secret_key | default "" | b64enc }}"
