name: lint-helm-test-template

on:
  []

jobs:
  test-n-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        paths:
          - "values.yaml"
    steps:
      - uses: actions/checkout@v3

      - name: test with  ${{ matrix.paths }}
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm lint . -f ${{ matrix.paths }}

      - uses: balchua/microk8s-actions@v0.3.0
        with:
          channel: '1.25/stable'
      - name: Test ${{ matrix.paths }}
        id: k8s
        run: |
          helm dependency build
          helm template paas . -f ${{ matrix.paths }}  -n paas > output.yaml
          kubectl create ns paas
          kubectl apply -f output.yaml -n paas
          sleep 150
          kubectl get pods -n paas
          kubectl get pods -n paas -o=jsonpath='{.items[*].status.containerStatuses}' | jq
