name: Release Charts

on:
  [push]
#  push:
#    tags:
#      - '*'

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}:${{ github.ref_name }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Save Helm charts
        run: |
          helm dependency update
          helm package ${{ github.workspace }} ${{ env.IMAGE_NAME }}

      - name: Push Charts to GHCR
        run: |
          helm push ${{ env.IMAGE_NAME }}
