name: Test Charts

on:
  [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        paths:
          - "values.yaml"
    steps:
      - uses: actions/checkout@v3

      - name: Lint with ${{ matrix.paths }}
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm lint . -f ${{ matrix.paths }}
      - name: Start k8s
        uses: helm/kind-action@v1.8.0
      - name: Test deployment with ${{ matrix.paths }}
        id: k8s
        run: |
          kubectl create ns paas
          helm dependency build
          helm -n paas install paas . -f ${{ matrix.paths }}
          kubectl -n paas wait --for=condition=ready --timeout 1m pod -l "app.kubernetes.io/component=vreapp"
          kubectl -n paas wait --for=condition=ready --timeout 1m pod -l "app.kubernetes.io/component=vreapi"
      - name: Print details
        if: ${{ failure() }}
        run: |
          echo "\n\n vreapp description"
          kubectl -n paas describe pod -l "app.kubernetes.io/component=vreapp"
          echo "\n\n vreapp logs"
          kubectl -n paas logs -l "app.kubernetes.io/component=vreapp"
          echo "\n\n vreapi description"
          kubectl -n paas describe pod -l "app.kubernetes.io/component=vreapi"
          echo "\n\n vreapi logs"
          kubectl -n paas logs -l "app.kubernetes.io/component=vreapi"
